[build-system]
requires = [
    "setuptools>=42",
    "wheel>=0.33.0",
    "cython>=3.0.7",
    "numpy>=2,<3",
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
junit_family = "legacy"
filterwarnings = [
    "ignore:.*numpy.dtype size changed.*:RuntimeWarning",
    "ignore:.*numpy.ufunc size changed.*:RuntimeWarning",
]

[tool.cibuildwheel]
archs = ["auto64"]
skip = "pp* *musllinux* cp38-* cp314-*"
test-requires = "pytest"
test-command = "pytest {project}/tests"

[tool.cibuildwheel.macos]
archs = ["native"]

[tool.cibuildwheel.linux]
manylinux-x86_64-image = "manylinux2014"