from __future__ import annotations

from libcpp import bool as cbool


class PyVertex:
    """Python-side snapshot of a geodesic::Vertex."""

    def __cinit__(self):
        ...

    @property
    def coords(self):
        """Return (x, y, z) tuple."""

    def __repr__(self):
        ...

class PyEdge:
    """Python-side snapshot of a geodesic::Edge."""

    def __cinit__(self):
        ...

    @property
    def vertex_ids(self):
        """Return (v0_id, v1_id) tuple."""

    def __repr__(self):
        ...

class PyFace:
    """Python-side snapshot of a geodesic::Face."""

    def __cinit__(self):
        ...

    def __repr__(self):
        ...

class PySurfacePoint:
    """Python-side snapshot of a geodesic::SurfacePoint."""

    def __cinit__(self):
        ...

    @property
    def x(self):
        ...

    @property
    def y(self):
        ...

    @property
    def z(self):
        ...

    @property
    def coords(self):
        ...

    @property
    def base_element_id(self):
        ...

    @property
    def point_type(self):
        ...

    @property
    def point_type_name(self):
        ...

    @property
    def is_vertex(self):
        ...

    @property
    def is_edge(self):
        ...

    @property
    def is_face(self):
        ...

    def __repr__(self):
        ...

class PyGeodesicAlgorithmExact:
    """
    Wrapper around C++ class GeodesicAlgorithmExact with exposed mesh data.
    """

    def __cinit__(self, _points, _faces):
        ...

    def getVertex(self, idx: int):
        """Return a PyVertex snapshot for vertex *idx*."""

    def getVertices(self):
        """Return a list of all PyVertex objects."""

    def getVerticesAsArray(self):
        """Return vertex coordinates as an Nx3 numpy array (fast path)."""

    def getEdge(self, idx: int):
        """Return a PyEdge snapshot for edge *idx*."""

    def getEdges(self):
        """Return a list of all PyEdge objects."""

    def getFace(self, idx: int):
        """Return a PyFace snapshot for face *idx*."""

    def getFaces(self):
        """Return a list of all PyFace objects."""

    def getEdgeCount(self):
        ...

    def getVertexCount(self):
        ...

    def getFaceCount(self):
        ...

    def getEdgeLengths(self):
        """Return current edge lengths as numpy array."""

    def getEdgeVertices(self):
        """Return edge vertex indices as Nx2 numpy array."""

    def getFaceVertices(self, fid: int):
        ...

    def setEdgeLength(self, edge_idx: int, new_length: float):
        ...

    def setEdgeLengthsFromArray(self, lengths):
        ...

    def getFaceEdgeLengths(self, face_idx: int):
        ...

    def setCornerAngle(self, face_idx: int, corner_idx: int, angle: float):
        ...

    def getCornerAngles(self, face_idx: int):
        ...

    def setSaddleOrBoundary(self, vertex_idx: int, value: cbool):
        ...

    def getSaddleOrBoundary(self, vertex_idx: int):
        ...

    def isEdgeBoundary(self, edge_idx: int):
        ...

    def getEdgeBoundaryVertices(self, edge_idx: int):
        ...

    def rebuildAlgorithm(self):
        ...

    def geodesicDistance(self, sourceIndex, targetIndex):
        """
        Calculates the geodesic distance and path between two vertices.
        Returns (path_length, path_points_Nx3).
        """

    def checkIndicesWithinLimits(self, indices):
        ...

    def propagate(self, source_indices, max_distance: float=GEODESIC_INF):
        ...

    def geodesicDistances(self, source_indices=None, target_indices=None, max_distance: float=GEODESIC_INF):
        """
        Calculates the distance of each target vertex from the closest
        source vertex.
        """

    def traceBack(self, target_idx: int):
        ...

    def __dealloc__(self):
        ...
_POINT_TYPE_NAMES = {VERTEX: 'VERTEX', EDGE: 'EDGE', FACE: 'FACE', UNDEFINED_POINT: 'UNDEFINED_POINT'}

def read_mesh_from_file(filename):
    """Read mesh from example files."""

# This file was generated by stubgen-pyx v0.2.2 from pygeodesic\geodesic.pyx